"""
Lightweight session authentication.

- Counsellors are an allow-list in config.yaml, each with a bcrypt password hash
  (created with `python -m app.manage_users`).
- On login we verify the password and issue a signed, expiring session cookie
  (HMAC-SHA256 over "email|expiry" using session_secret — no server-side session
  store needed, and tampering is detected).
- Optional Google Workspace OAuth can be enabled instead of / in addition to
  passwords (see docs/04-authentication.md); the verify_google_token hook is
  provided but disabled by default so the system runs with zero external auth
  dependencies.

Passwords are never logged and never leave the server. Claude never handles the
plaintext — hashes are generated by the admin via the CLI.
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import time
from typing import Optional, Tuple

from .config import Settings, Counsellor

try:
    import bcrypt
except Exception:  # pragma: no cover
    bcrypt = None


# --- password hashing --------------------------------------------------------
def hash_password(plain: str) -> str:
    if bcrypt is None:
        raise RuntimeError("bcrypt is required to hash passwords (pip install bcrypt).")
    return bcrypt.hashpw(plain.encode("utf-8"), bcrypt.gensalt()).decode("ascii")


def verify_password(plain: str, hashed: str) -> bool:
    if not hashed:
        return False
    if bcrypt is None:  # pragma: no cover
        # extremely defensive fallback: constant-time compare of sha256 (only if
        # the admin stored a "sha256:" hash). Prefer bcrypt in all real setups.
        if hashed.startswith("sha256:"):
            digest = hashlib.sha256(plain.encode()).hexdigest()
            return hmac.compare_digest(digest, hashed[7:])
        return False
    try:
        return bcrypt.checkpw(plain.encode("utf-8"), hashed.encode("ascii"))
    except Exception:
        return False


# --- signed session token ----------------------------------------------------
def _sign(secret: str, payload: str) -> str:
    sig = hmac.new(secret.encode(), payload.encode(), hashlib.sha256).digest()
    return base64.urlsafe_b64encode(sig).decode("ascii").rstrip("=")


def make_token(settings: Settings, email: str) -> str:
    exp = int(time.time()) + settings.session_hours * 3600
    payload = f"{email.lower()}|{exp}"
    body = base64.urlsafe_b64encode(payload.encode()).decode("ascii").rstrip("=")
    return f"{body}.{_sign(settings.session_secret, payload)}"


def verify_token(settings: Settings, token: str) -> Optional[str]:
    """Return the email if the token is valid and unexpired, else None."""
    if not token or "." not in token:
        return None
    body, sig = token.rsplit(".", 1)
    try:
        pad = "=" * (-len(body) % 4)
        payload = base64.urlsafe_b64decode(body + pad).decode()
    except Exception:
        return None
    expected = _sign(settings.session_secret, payload)
    if not hmac.compare_digest(sig, expected):
        return None
    try:
        email, exp = payload.split("|", 1)
        if int(exp) < int(time.time()):
            return None
        return email
    except Exception:
        return None


# --- login -------------------------------------------------------------------
def authenticate(settings: Settings, email: str, password: str
                 ) -> Tuple[bool, str, Optional[Counsellor]]:
    c = settings.counsellor_by_email(email)
    if c is None or not c.active:
        return False, "Unknown or inactive account.", None
    if not verify_password(password, c.password_hash):
        return False, "Incorrect password.", None
    return True, "", c


# --- optional Google OAuth (disabled unless configured) ----------------------
def verify_google_token(settings: Settings, id_token_str: str
                        ) -> Tuple[bool, str, Optional[Counsellor]]:  # pragma: no cover
    if not settings.google_oauth_enabled:
        return False, "Google login is not enabled.", None
    try:
        from google.oauth2 import id_token as gid
        from google.auth.transport import requests as grequests
        info = gid.verify_oauth2_token(id_token_str, grequests.Request(),
                                       settings.google_client_id)
        email = (info.get("email") or "").lower()
        if settings.allowed_email_domain and \
                not email.endswith("@" + settings.allowed_email_domain.lower()):
            return False, "Email domain not allowed.", None
        c = settings.counsellor_by_email(email)
        if c is None or not c.active:
            return False, "Account not provisioned.", None
        return True, "", c
    except Exception as e:  # noqa: BLE001
        return False, f"Google token invalid: {e}", None
